apiVersion: apps/v1
kind: Deployment
metadata:
  name: mes-ion-api
  labels:
    app: mes-ion-api
    restartForPostgresDB: secrets
    app.kubernetes.io/name: mes-ion-api
    app.kubernetes.io/part-of: mes-ion
    app.kubernetes.io/component: api
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mes-ion-api
  template:
    metadata:
      labels:
        app: mes-ion-api
        system: mes
        app.kubernetes.io/name: mes-ion-api
        app.kubernetes.io/part-of: mes-ion
        app.kubernetes.io/component: api
    spec:
      nodeSelector: 
        kubernetes.io/os: linux
      containers:
      - name: ion-api
        image: docker.io/pingisappdev/mes-ion-api:${TAG_NAME}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 9229
          name: debug
        envFrom:
        - secretRef:
            name: ion-api-secrets
            optional: true
        - configMapRef:
            name: mes-system-env
            optional: true
        - configMapRef:
            name: mes-ion-api-config
        env: []
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      imagePullSecrets:
      - name: docker-pat