apiVersion: v1
kind: Service
metadata:
  name: mes-ion-api
  labels:
    app: mes-ion-api
    app.kubernetes.io/name: mes-ion-api
    app.kubernetes.io/part-of: mes-ion
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  - port: 9229
    targetPort: 9229
    protocol: TCP
    name: debug
  selector:
    app: mes-ion-api