version: '3.8'

services:
  api:
    build:
      context: .
      target: development
    container_name: mes-ion-api
    ports:
      - "3000:3000"
      - "9090:9090"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:password@postgres:5432/mes_ion_api
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./docs:/app/docs
      - ./scripts:/app/scripts
      - /app/node_modules
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - mes-network

  postgres:
    image: postgres:15-alpine
    container_name: mes-ion-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mes_ion_api
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mes-network

  redis:
    image: redis:7-alpine
    container_name: mes-ion-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - mes-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: mes-ion-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - mes-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: mes-ion-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mes.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - mes-network

volumes:
  postgres-data:
  redis-data:
  rabbitmq-data:

networks:
  mes-network:
    driver: bridge