- op: replace
  path: /spec/template/spec/containers/0/command
  value: ["npm", "run", "dev"]
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: NODE_ENV
    value: "development"