apiVersion: v1
kind: Secret
metadata:
  name: ion-api-secrets
  labels:
    app: mes-ion-api
type: Opaque
stringData:
  # ION API Configuration
  ION_TENANT_ID: "your-actual-tenant-id"
  ION_CLIENT_ID: "your-actual-client-id"
  ION_CLIENT_SECRET: "your-actual-client-secret"
  ION_USERNAME: "your-ion-username"
  ION_PASSWORD: "your-ion-password"
  ION_TOKEN_ENDPOINT: "https://mingle-ionapi.inforcloudsuite.com/YOUR-TENANT/as/token.oauth2"
  ION_API_ENDPOINT: "https://mingle-ionapi.inforcloudsuite.com/YOUR-TENANT"
  ION_SUBSCRIPTION_KEY: "your-subscription-key"
  ION_ORGANIZATION: "your-organization"
  
  # Security
  API_KEY_SALT: "your-secure-random-salt"
  WEBHOOK_SECRET: "your-webhook-secret"